server:
  port: 8765

info:
  component: Edge Server

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 3
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
    # Default values comes from org.springframework.cloud.netflix.eurek.EurekaClientConfigBean
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: "*"
  prefix: /api/guestdriven
  routes:
    #gdapi: 
     # path: /guestdriven/**
      #serviceId: gdapi
    checkin:
      path: /checkin/**
      serviceId: checkin
    fetchbookings:
      path: /fetchbookings/**
      serviceId: fetchbookings
      
    
      
hystrix:
   command:
      default:
         execution:
            isolation:
               thread:
                 timeoutInMilliseconds: 60000
                 
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 60000

logging:
  level:
    ROOT: WARN
    org.springframework.web: WARN
    # Set DEBUG level on Hystrix to get an error message when a fallback method is used.
    com.netflix.hystrix: DEBUG